name: CI/CD Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Change to the desired Node.js version
        cache: 'npm'     # Enable caching for npm dependencies

    # Install dependencies
    - name: Install dependencies
      run: npm ci # Faster and consistent installs compared to npm install

    # Cache node_modules to avoid reinstalling
    - name: Cache node_modules
      id: npm-cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node_modules-

    # Build the application
    - name: Build the application
      run: npm run build

    # Run tests
    - name: Run tests
      run: npm test

    # Deploy the application
    - name: Deploy the application
      if: github.ref == 'refs/heads/main' # Only deploy on the main branch
      run: npm run deploy
